name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download Tools
        run: |
          sudo apt update
          sudo apt install -y unzip wget
          wget https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2024-11-21/oss-cad-suite-linux-x64-20241121.tgz && tar -xf oss-cad-suite-linux-x64-20241121.tgz && export PATH="./oss-cad-suite/bin:$PATH"
          wget https://github.com/zachjs/sv2v/releases/download/v0.0.12/sv2v-Linux.zip && unzip sv2v-Linux.zip && export PATH="./sv2v-Linux/:$PATH"
          echo "$GITHUB_WORKSPACE/oss-cad-suite/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/zachjs-sv2v" >> $GITHUB_PATH

      - run: make lint
      - run: make sim
      - run: make gls
      - run: make icestorm_icebreaker_gls

      - run: make clean
